#pragma once
#include "bytecode/compileBytecode.hpp"
#include <ds/parser/tokens.hpp>
#include <optional>

namespace ds
{
	class Type;
	struct ParsedScope;
	struct ErrorContext;

	/**
	 * @brief
	 * The result of any expression, containing it's generated bytecode, type, and information.
	 *
	 * An example for an expression would be `1 + 1`, where both 1 and 1 + 1 are expressions, and
	 * 1 + 1 forms a combined expression that adds both types.
	 */
	struct ExpressionResult
	{
		/// Is this a valid parsed expression?
		bool valid = false;
		/// Can this expression be discarded (ignoring it's return value) without an error
		bool discardable = false;
		/// Optional code used to write this expression. If this is empty, this expression is read-only.
		std::optional<BytecodeBuffer> setCode;
		/// The type of this expression. Can be null if the expression doesn't return any value.
		Type* type = nullptr;
		/// The bytecode that's used to read this expression.
		BytecodeBuffer code;

		void discard(Token at, ErrorContext* errors) const;

		BytecodeBuffer unrefHere(ParsedScope* with);

		/**
		 * @brief
		 * Tries to convert this expression into the given type, if possible.
		 *
		 * This modifies this expression object instead of returning a new expression.
		 * Only use this if you know the type has to be cast, this will add a script error if it fails.
		 *
		 * @param at
		 * The token representing the expression for error handling.
		 * @param target
		 * The target type to compile to
		 * @param with
		 * The scope in which to perform this operation
		 * @param errors
		 * Error context to report to if an error occurs.
		 */
		void compileToType(Token at, Type* target, ParsedScope* with, ErrorContext* errors);
	};
} // namespace ds